Added colours

diff --git a/.github/workflows/client.yml b/.github/workflows/client.yml
--- a/.github/workflows/client.yml
+++ b/.github/workflows/client.yml
@@ -23,4 +23,5 @@ jobs:
           if echo "$out" | grep -qi "Success"; then
             echo "::notice::$out"; printf "\033[32m SUCCESS"
           else
-            echo "::error::$out"; printf "\033[31m ERROR"
+            echo "::error::$out"; printf "\033[31m ERROR"; exit 1
+          fi
